# Data specific parameters 
vertical_variable: "F001"
lateral_variable: "F002"

# Analysis specific parameters
sampling_rate_hz: 32               # if the sampling frequency changes, change it here
amplitude_threshold: 0.05         # minimum difference between peak and bottom in m
significant_window_sec: 5         # seconds to look around each peak
event_gap_sec: 60                 # max gap between peaks in same event
plot_padding_sec: 60              # padding before/after events